/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhatIsMoqRouteImport } from './routes/what-is-moq'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as MeetupsIndexRouteImport } from './routes/meetups.index'
import { Route as MeetupsMeetupIdRouteImport } from './routes/meetups.$meetupId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminMeetupsRouteImport } from './routes/_authenticated/admin/meetups'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin/members'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin/resources'
import { Route as ApiPublicCalendarMeetupIdDoticsRouteImport } from './routes/api/public/calendar.$meetupId[.]ics'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsMoqRoute = WhatIsMoqRouteImport.update({
  id: '/what-is-moq',
  path: '/what-is-moq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MeetupsIndexRoute = MeetupsIndexRouteImport.update({
  id: '/meetups/',
  path: '/meetups/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetupsMeetupIdRoute = MeetupsMeetupIdRouteImport.update({
  id: '/meetups/$meetupId',
  path: '/meetups/$meetupId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMeetupsRoute =
  AuthenticatedAdminMeetupsRouteImport.update({
    id: '/admin/meetups',
    path: '/admin/meetups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/admin/members',
    path: '/admin/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/admin/resources',
    path: '/admin/resources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCalendarMeetupIdDoticsRoute =
  ApiPublicCalendarMeetupIdDoticsRouteImport.update({
    id: '/api/public/calendar/$meetupId.ics',
    path: '/api/public/calendar/$meetupId.ics',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/what-is-moq': typeof WhatIsMoqRoute
  '/account': typeof AuthenticatedAccountRoute
  '/meetups/$meetupId': typeof MeetupsMeetupIdRoute
  '/meetups/': typeof MeetupsIndexRoute
  '/admin/meetups': typeof AuthenticatedAdminMeetupsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/calendar/$meetupId.ics': typeof ApiPublicCalendarMeetupIdDoticsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/what-is-moq': typeof WhatIsMoqRoute
  '/account': typeof AuthenticatedAccountRoute
  '/meetups/$meetupId': typeof MeetupsMeetupIdRoute
  '/meetups': typeof MeetupsIndexRoute
  '/admin/meetups': typeof AuthenticatedAdminMeetupsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/calendar/$meetupId.ics': typeof ApiPublicCalendarMeetupIdDoticsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/what-is-moq': typeof WhatIsMoqRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/meetups/$meetupId': typeof MeetupsMeetupIdRoute
  '/meetups/': typeof MeetupsIndexRoute
  '/_authenticated/admin/meetups': typeof AuthenticatedAdminMeetupsRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/calendar/$meetupId.ics': typeof ApiPublicCalendarMeetupIdDoticsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/resources'
    | '/terms'
    | '/what-is-moq'
    | '/account'
    | '/meetups/$meetupId'
    | '/meetups/'
    | '/admin/meetups'
    | '/admin/members'
    | '/admin/resources'
    | '/admin/'
    | '/api/public/calendar/$meetupId.ics'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/resources'
    | '/terms'
    | '/what-is-moq'
    | '/account'
    | '/meetups/$meetupId'
    | '/meetups'
    | '/admin/meetups'
    | '/admin/members'
    | '/admin/resources'
    | '/admin'
    | '/api/public/calendar/$meetupId.ics'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/resources'
    | '/terms'
    | '/what-is-moq'
    | '/_authenticated/account'
    | '/meetups/$meetupId'
    | '/meetups/'
    | '/_authenticated/admin/meetups'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/'
    | '/api/public/calendar/$meetupId.ics'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  TermsRoute: typeof TermsRoute
  WhatIsMoqRoute: typeof WhatIsMoqRoute
  MeetupsMeetupIdRoute: typeof MeetupsMeetupIdRoute
  MeetupsIndexRoute: typeof MeetupsIndexRoute
  ApiPublicCalendarMeetupIdDoticsRoute: typeof ApiPublicCalendarMeetupIdDoticsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-moq': {
      id: '/what-is-moq'
      path: '/what-is-moq'
      fullPath: '/what-is-moq'
      preLoaderRoute: typeof WhatIsMoqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/meetups/': {
      id: '/meetups/'
      path: '/meetups'
      fullPath: '/meetups/'
      preLoaderRoute: typeof MeetupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetups/$meetupId': {
      id: '/meetups/$meetupId'
      path: '/meetups/$meetupId'
      fullPath: '/meetups/$meetupId'
      preLoaderRoute: typeof MeetupsMeetupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/meetups': {
      id: '/_authenticated/admin/meetups'
      path: '/admin/meetups'
      fullPath: '/admin/meetups'
      preLoaderRoute: typeof AuthenticatedAdminMeetupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/admin/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/calendar/$meetupId.ics': {
      id: '/api/public/calendar/$meetupId.ics'
      path: '/api/public/calendar/$meetupId.ics'
      fullPath: '/api/public/calendar/$meetupId.ics'
      preLoaderRoute: typeof ApiPublicCalendarMeetupIdDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminMeetupsRoute: typeof AuthenticatedAdminMeetupsRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminMeetupsRoute: AuthenticatedAdminMeetupsRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  TermsRoute: TermsRoute,
  WhatIsMoqRoute: WhatIsMoqRoute,
  MeetupsMeetupIdRoute: MeetupsMeetupIdRoute,
  MeetupsIndexRoute: MeetupsIndexRoute,
  ApiPublicCalendarMeetupIdDoticsRoute: ApiPublicCalendarMeetupIdDoticsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
